### ISSUE TITLE
Error when stop program

### ISSUE THREAD

**Issue by Loic691** [petergridge/Irrigation-V5#17]
When I stop on of my 2 programs, I have the following error

```
Logger: homeassistant.core
Source: custom_components/irrigationprogram/__init__.py:75
Integration: Irrigation controller ([documentation](https://github.com/petergridge/irrigation-v5), [issues](https://github.com/petergridge/irrigation-v5/issues))
First occurred: 17:52:36 (2 occurrences)
Last logged: 17:55:29

Error executing service: <ServiceCall irrigationprogram.stop_programs (c:01GX6FGNPJTMCX3KSMVVXCDDPC): ignore=Prog2>
Error executing service: <ServiceCall irrigationprogram.stop_programs (c:01GX6FNZ1CDAQC8H6KA55X64R9): ignore=Prog2>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1826, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1845, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/config/custom_components/irrigationprogram/__init__.py", line 75, in async_stop_programs
    if hass.states.get(device).state == "on":
AttributeError: 'NoneType' object has no attribute 'state'
```

**Comment by petergridge** [comment]
Hi, I can't recreate this issue. 

This could occur if you have deleted or renamed one of the zone switches without updating the configuration for the irrigation program.

Can you send me more information on your configuration, what switch devices you are using etc.
