### ISSUE TITLE
Program never runs

### ISSUE THREAD

**Issue by robsonfelix** [petergridge/Irrigation-V5#47]
I am getting the following error message. I have uninstalled/re-installed multiple times without luck. I have multiple programs and each of them use different parameters. They all use a inputnumber for runtime.

Logger: homeassistant
Source: custom_components/irrigationprogram/switch.py:564
Integration: Irrigation controller ([documentation](https://github.com/petergridge/irrigation-v5), [issues](https://github.com/petergridge/irrigation-v5/issues))
First occurred: October 20, 2023 at 8:00:00 PM (6 occurrences)
Last logged: 12:40:23 PM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/irrigationprogram/switch.py", line 631, in async_turn_on
    zones = await self.build_run_script(False)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/irrigationprogram/switch.py", line 564, in build_run_script
    zone.run_time(repeats=zone.repeat_value(),scheduled=self.scheduled)
    ^^^^^^^^^^^^^
AttributeError: 'IrrigationZone' object has no attribute 'run_time'

**Comment by robsonfelix** [comment]
After adding "min" to Unit Of Measurement, the error still persists but the log changed slightly.

Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:226
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 12:56:54 PM (1 occurrences)
Last logged: 12:56:54 PM

[140481934696640] 'IrrigationZone' object has no attribute 'run_time'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 226, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 2012, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2049, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 235, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 876, in entity_service_call
    response_data = await _handle_entity_call(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 948, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/irrigationprogram/switch.py", line 631, in async_turn_on
    zones = await self.build_run_script(False)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/irrigationprogram/switch.py", line 564, in build_run_script
    zone.run_time(repeats=zone.repeat_value(),scheduled=self.scheduled)
    ^^^^^^^^^^^^^
AttributeError: 'IrrigationZone' object has no attribute 'run_time'

**Comment by robsonfelix** [comment]
I had to roll back to 5.4.2. This is not working on newer versions.

**Comment by petergridge** [comment]
Hi,  I'm on holiday at the moment and won't be able to follow this up for another 3 weeks

**Comment by petergridge** [comment]
Hi, Can you send me a screenshot of your configuration and any additional details of the objects you are using, hopefully I can recreate the issue in my dev environment

**Comment by petergridge** [comment]
Hi I have found the problem will have a fix out shortly

**Comment by petergridge** [comment]
Hi, V5.4.6 Beta fixes the problem introduced in my earlier beta, sorry about the problem.

Can you install and let me know if this resolves your problem and I will close this issue off.

Cheers
Pete

**Comment by petergridge** [comment]
I have added some error handling to try and identify the problem in V5.4.14-alpha. You should see a message like "Could not find Program implementation 'switch.program_name', ignored" Hopefully this will let us track down the issue.
