### ISSUE TITLE
time_date issue

### ISSUE THREAD

**Issue by DLowe77** [petergridge/Irrigation-V5#5]
Good day

I'm experiencing an error when running the program.

When utilising the switch or the 'run' button on the card, the switch fails due to a time_date error.

time_date is defined in the config and shows on the overview page.

On the lovelace card, there is also an oddity next to the 'run' buttons for each zone except for the 1st zone.  This shows a static date of 9 January 2023, 2:35:14PM for each, and is not related to the Time input helper value.

Any idea of what I might have done wrong?

thanks

Logger: homeassistant.components.websocket_api.http.connection
Source: util/dt.py:132
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 3:53:33 PM (5 occurrences)
Last logged: 4:19:38 PM

[548191012224] not a valid date/time.
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 200, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1755, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1792, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 678, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 958, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 715, in _handle_entity_call
    await result
  File "/config/custom_components/irrigationprogram/switch.py", line 430, in async_turn_on
    if zone.should_run() is False:
  File "/config/custom_components/irrigationprogram/irrigationzone.py", line 254, in should_run
    - dt_util.as_timestamp(self._last_ran)
  File "/usr/src/homeassistant/homeassistant/util/dt.py", line 132, in as_timestamp
    raise ValueError("not a valid date/time.")
ValueError: not a valid date/time.
 
![image](https://user-images.githubusercontent.com/53297584/213481396-6cee6f5e-9aa7-4357-943a-a34ef350aeb3.png)

**Comment by petergridge** [comment]
Hi @DLowe77,

Please download the latest version V5.1.19.1 not the Alpha release, I must have not uploaded the latest change, I had found and fixed this issue previously.

Cheers
Pete

**Comment by DLowe77** [comment]
Thanks Pete

Got a update push.

Working like a charm!

Thank you
Dylan
