### ISSUE TITLE
Timeout on getting the data from rainbird controller / possible to add a configurable delay between send/query commands?

### ISSUE THREAD

**Issue by jellyneck84** [petergridge/Irrigation-V5#56]
Hello @petergridge ,

i noticed an issue with my rainbird controller, which is maybe caused by this known issue: https://github.com/home-assistant/core/issues/102498

Seems the rainbird controller does not like too many requests in a short period of time. Do you think  we can workaround this somehow in the irrigation programm?

##### Core Log #####
The irrigation program shows the following errors:
Logger: custom_components.irrigationprogram.switch
Source: custom_components/irrigationprogram/switch.py:724
Integration: Irrigation controller (documentation, issues)
First occurred: 23. Februar 2024 um 22:06:32 (15 occurrences)
Last logged: 08:56:25

Significant latency has been detected, unexpected behaviour may occur, switch.rain_bird_sprinkler_2
Significant latency has been detected, unexpected behaviour may occur, switch.rain_bird_sprinkler_3
Significant latency has been detected, unexpected behaviour may occur, switch.rain_bird_sprinkler_4
Significant latency has been detected, unexpected behaviour may occur, switch.rain_bird_sprinkler_5

Logger: homeassistant.core
Source: core.py:2295
First occurred: 23. Februar 2024 um 22:06:31 (9 occurrences)
Last logged: 08:56:23

Error executing service: <ServiceCall switch.turn_on (c:01HQBWWY91Y40Q09V4R707XA6J): entity_id=['switch.rain_bird_sprinkler_3']>
Error executing service: <ServiceCall switch.turn_on (c:01HQBWXKS8R9CX4QKMPXWP0CCP): entity_id=['switch.rain_bird_sprinkler_5']>
Error executing service: <ServiceCall rainbird.start_irrigation (c:01HQJ6HADWC6GB2BXBB5WPW6BY): entity_id=['switch.rain_bird_sprinkler_2'], duration=1.0>
Error executing service: <ServiceCall rainbird.start_irrigation (c:01HQJ6HN5Z9DBFEHK12TDZVB5H): entity_id=['switch.rain_bird_sprinkler_3'], duration=1.0>
Error executing service: <ServiceCall rainbird.start_irrigation (c:01HQJ6M6DMGS2EA50ZPX2H5C5R): entity_id=['switch.rain_bird_sprinkler_5'], duration=1.0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/pyrainbird/async_client.py", line 134, in request
    resp.raise_for_status()
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 1060, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 503, message='Service Unavailable', url=URL('http://192.168.60.21/stick')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/rainbird/switch.py", line 95, in async_turn_on
    await self.coordinator.controller.irrigate_zone(
  File "/usr/local/lib/python3.12/site-packages/pyrainbird/async_client.py", line 327, in irrigate_zone
    await self._process_command(
  File "/usr/local/lib/python3.12/site-packages/pyrainbird/async_client.py", line 484, in _process_command
    decrypted_data = await self._tunnelSip(
                     ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyrainbird/async_client.py", line 468, in _tunnelSip
    result = await self._local_client.request(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyrainbird/async_client.py", line 137, in request
    raise RainbirdDeviceBusyException(
pyrainbird.exceptions.RainbirdDeviceBusyException: Rain Bird device is busy; Wait and try again

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 2295, in _run_service_call_catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 2316, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 892, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 962, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/rainbird/switch.py", line 100, in async_turn_on
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Rain Bird device is busy; Wait and try again

Logger: homeassistant.core
Source: core.py:2295
First occurred: 23. Februar 2024 um 22:06:26 (4 occurrences)
Last logged: 08:56:22

Error executing service: <ServiceCall switch.turn_off (c:01HQBWMQ5E43ANS645K6F82RHH): entity_id=['switch.rain_bird_sprinkler_1']>
Error executing service: <ServiceCall switch.turn_off (c:01HQBWWGJCSNVZJNREFAM115J0): entity_id=['switch.rain_bird_sprinkler_1']>
Error executing service: <ServiceCall switch.turn_off (c:01HQJ6H7FMXWQVB3JBVNG4M54H): entity_id=['switch.rain_bird_sprinkler_1']>
Error executing service: <ServiceCall switch.turn_off (c:01HQJ6M3FAYXC3BW3STB1112X4): entity_id=['switch.rain_bird_sprinkler_4']>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/pyrainbird/async_client.py", line 134, in request
    resp.raise_for_status()
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 1060, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 503, message='Service Unavailable', url=URL('http://192.168.60.21/stick')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/rainbird/switch.py", line 111, in async_turn_off
    await self.coordinator.controller.stop_irrigation()
  File "/usr/local/lib/python3.12/site-packages/pyrainbird/async_client.py", line 333, in stop_irrigation
    await self._process_command(lambda resp: True, "StopIrrigationRequest")
  File "/usr/local/lib/python3.12/site-packages/pyrainbird/async_client.py", line 484, in _process_command
    decrypted_data = await self._tunnelSip(
                     ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyrainbird/async_client.py", line 468, in _tunnelSip
    result = await self._local_client.request(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyrainbird/async_client.py", line 137, in request
    raise RainbirdDeviceBusyException(
pyrainbird.exceptions.RainbirdDeviceBusyException: Rain Bird device is busy; Wait and try again

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 2295, in _run_service_call_catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 2316, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 892, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 962, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/rainbird/switch.py", line 113, in async_turn_off
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Rain Bird device is busy; Wait and try again

**Comment by petergridge** [comment]
Hi, 

It looks like the rainbird app is causing the issues. It is worrying that it fails on the turn off command. Not much I can do on my side.

Reading the code it appears that the device may have problems if multiple connections are attempted. Do you have your phone or other device also accessing the rainbird while the irrigation is running?

For a 503 error it has a built in retry of 3 attempts before failing.

Sorry I can't be more helpful.

Pete

**Comment by jellyneck84** [comment]
Thanks @petergridge for looking into it. I checked some logs by myself and did some tests, i found the same. 
I'm not connected with my mobile phone to the controller, nothing else is connected.

Strange is, that the connection loss/crash of the integration is only happening in automations. I tested manually to switch on/off the valves, and i could not produce a connection loss.

I created an issue in the rainbird integration, i'm sure the code owners will have a look.
https://github.com/home-assistant/core/issues/111708

**Comment by allenporter** [comment]
> Reading the code it appears that the device may have problems if multiple connections are attempted. 

Wanted to confirm this is true. The device does not like to have multiple commands sent at once.

Does this issue turn on/off commands serially?

**Comment by jellyneck84** [comment]
@petergridge see https://github.com/home-assistant/core/issues/102498 , first tests after the change from Allen looks good, if i include a break between the zones (10 secs). THis is my current test config:
![image](https://github.com/petergridge/Irrigation-V5/assets/68947111/c722ce0d-5d8a-4826-aae5-1de561750fa8)

![image](https://github.com/petergridge/Irrigation-V5/assets/68947111/101eeb9f-78d3-43c1-9223-c8b1bb99151e)

Will do more tests to confirm it 100 %....

**Comment by jellyneck84** [comment]
Looks great for now.
![image](https://github.com/petergridge/Irrigation-V5/assets/68947111/e2980cc2-3b56-487e-8354-18d732aba1ee)
